# Generated by Django 3.1.2 on 2020-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('star', models.IntegerField(default=0)),
                ('comment', models.TextField()),
            ],
        ),
    ]
