# Generated by Django 3.1.4 on 2020-12-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('cn_name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('com_num', models.CharField(max_length=8)),
                ('commodity', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('on_sale', models.DateTimeField()),
                ('avg_sentiment', models.CharField(default=None, max_length=16)),
                ('avg_score', models.CharField(default=None, max_length=20)),
                ('commodity_from', models.CharField(max_length=16)),
                ('detail_link', models.TextField()),
                ('comment_count', models.IntegerField()),
                ('comment_link', models.TextField()),
                ('last_comment', models.CharField(default='', max_length=32)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.category')),
            ],
            options={
                'db_table': 'Commodity',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(max_length=16)),
                ('sentiment_score', models.CharField(max_length=20)),
                ('comment_time', models.DateTimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.category')),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.commodity')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
